### ISSUE TITLE
Wont run correctly

### ISSUE THREAD

**Issue by Elimitless** [POE-Addon-Launcher/PoE-Addon-Launcher#32]
[PAL_DEBUGGER_LOG.txt](https://github.com/POE-Addon-Launcher/PoE-Addon-Launcher/files/2753268/PAL_DEBUGGER_LOG.txt)
After using the update all button, the program get stuck downloading 1 addon (POE-Trades-Companion) indefinably. After force closing PAL and restarting it, it will no longer launch any kind of GUI, however it does appear in the system tray. To fix this i have to delete the POE-Trades-Companion folder in addons. This is repeatable only on updating POE-Trades-Companion.

**Comment by POE-Addon-Launcher** [comment]
Interesting must be some weird bug with POE-Trades-Companion not playing nice with update all, going to investigate.

**Comment by POE-Addon-Launcher** [comment]
I think I've fixed it, should work on b18.
