### ISSUE TITLE
Unable to launch the programm after installation

### ISSUE THREAD

**Issue by GlitchingCloud** [POE-Addon-Launcher/PoE-Addon-Launcher#9]
Issue: Program closes shortly after the loading screen.

Running launcher thru cmd yelds following:

> E:\PAL>java -jar POE.Addon.Launcher.1.4(1).jar
> сен 25, 2018 12:05:16 PM javafx.fxml.FXMLLoader$ValueElement processValue
> WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.181
> Accessing github for releases
> Got all 11 releases!
> Checking if we're up to date
> b11.jar | b11 | https://github.com/POE-Addon-Launcher/Core/releases/download/b11/b11.jar
> Up to date, launching program!
> E:\PAL>

Java version:

> java version "1.8.0_181"
> Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Specs:
> Win 10 Enterprise
> AMD Ryzen 5 1500X
> 8 GB DDR 4 RAM
> GTX 1060 6GB

I've tried wiping out the installation from my PC in order to reinstall, but only thing I could do was deleting the installation folder, since I have no idea where the rest of the files/data might be and there is no unistall option anywhere in the sights. 
PC restart does not seem to help. 

All provided information might not be useful in the investigation process, but that's all I could gather by my self. Please let me know if I can provide you with anything else

**Comment by GlitchingCloud** [comment]
I've managed to get program running by using v1.3 release.
I've also managed to gather some error logs:
Issue seem to be launcher .jar file that i've downloaded earlier. Removing it fixed the issue
Log:

> E:\PAL>java -jar C:\Users\User\Downloads\PoE.Addon.Launcher.v1.3.jar
> сен 25, 2018 12:22:00 PM javafx.fxml.FXMLLoader$ValueElement processValue
> WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.181
> Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>         at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
>         at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
>         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
>         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
>         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
>         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
>         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
>         at javafx.event.Event.fireEvent(Event.java:198)
>         at javafx.scene.Node.fireEvent(Node.java:8411)
>         at javafx.scene.control.Button.fire(Button.java:185)
>         at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
>         at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
>         at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
>         at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
>         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
>         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
>         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
>         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
>         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
>         at javafx.event.Event.fireEvent(Event.java:198)
>         at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
>         at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
>         at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
>         at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
>         at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
>         at com.sun.glass.ui.View.notifyMouse(View.java:937)
>         at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>         at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
>         at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at sun.reflect.misc.Trampoline.invoke(Unknown Source)
>         at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
>         at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
>         ... 48 more
> Caused by: javafx.fxml.LoadException:
> file:/C:/Users/User/Downloads/PoE.Addon.Launcher.v1.3.jar!/Launcher.fxml
> 
>         at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
>         at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
>         at GUI.LauncherUI.start(LauncherUI.java:23)
>         at GUI.Configurator_Controller.step4(Configurator_Controller.java:265)
>         at GUI.Configurator_Controller.ButtonNext(Configurator_Controller.java:78)
>         ... 58 more
> Caused by: java.lang.NumberFormatException: For input string: "POE.Addon.Launcher.1.4(1)"
>         at java.lang.NumberFormatException.forInputString(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at java.lang.Integer.parseInt(Unknown Source)
>         at GUI.LauncherUI_Controller.isNewer(LauncherUI_Controller.java:67)
>         at GUI.LauncherUI_Controller.cleanUp(LauncherUI_Controller.java:86)
>         at GUI.LauncherUI_Controller.initialize(LauncherUI_Controller.java:36)
>         at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
>         ... 68 more
>

**Comment by POE-Addon-Launcher** [comment]
One thing that strikes me as odd here is that there seems to be something wrong in the "ButtonNext" function that was introduced in v1.4 that wasn't there in v1.3.

I also notice a java.lang.NumberFormatException, which is odd.

**Comment by POE-Addon-Launcher** [comment]
I notice your CMD says "сен", I'm thinking this might be caused by a localization issue.

**Comment by POE-Addon-Launcher** [comment]
Ok I think I know why you got a java.lang.NumberFormatException, it's because your launcher is called: "POE.Addon.Launcher.1.4(1)" and you put it in the "Core" folder.

Try this to fix it:

Put launcher anywhere that's not the Addons or Core folder, and rename it to POE.Addon.Launcher.1.4 without the (1).

That should fix the java.lang.NumberFormatException @GlitchingCloud

**Comment by Razunter** [comment]
Don't know if it's the same issue, but in my case the Launcher closes too without any error messages.
I've deleted installed files while trying to figure this out and now the launcher doesn't even redownloads them. Manually downloaded b11.jar and it outputs this error:
```
Exception in thread "main" java.lang.NullPointerException
        at java.desktop/sun.awt.SunToolkit.getImageFromHash(Unknown Source)
        at java.desktop/sun.awt.SunToolkit.getImage(Unknown Source)
        at Backend.SystemTrayHandler.createSystemTray(SystemTrayHandler.java:30)
        at Launcher.main(Launcher.java:27)
```

**Comment by POE-Addon-Launcher** [comment]
SystemTrayHandler is also an issue someone else had, I currently have no idea what it's caused by, I'm currently creating a debugger program to help with it.

**Comment by POE-Addon-Launcher** [comment]
@Razunter  in an effort to find the bug that's causing that could you run PAL Debugger and give me the "PAL_DEBUGGER_LOG.txt" it will create?

https://github.com/POE-Addon-Launcher/POE-DEBUGGER/releases

**Comment by POE-Addon-Launcher** [comment]
That is very interesting, it shows that everything is "working" as it should, if I may ask what's your OS and what JRE are you running?

**Comment by Razunter** [comment]
Windows 10 x64 1803, jre-10.0.1

**Comment by POE-Addon-Launcher** [comment]
Alright, I'm starting to think this might be a JRE10 bug then. Ok I've changed a few things, can you try this "b12.jar" and see if you still get the system tray error?

(You don't have to put it in Core you can just run it from anywhere)
[b11.zip](https://github.com/POE-Addon-Launcher/PoE-Addon-Launcher/files/2418268/b11.zip)

**Comment by Razunter** [comment]
```
Exception in thread "main" java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
        at Backend.SystemTrayHandler.createSystemTray(SystemTrayHandler.java:35)
        at Launcher.main(Launcher.java:27)
```

**Comment by POE-Addon-Launcher** [comment]
Well at least we're getting further... I'll probably write something to detect jre10 and just disable systemtray fro the moment.

**Comment by GlitchingCloud** [comment]
> Put launcher anywhere that's not the Addons or Core folder, and rename it to POE.Addon.Launcher.1.4 without the (1).

It fixed the problem for the 1.3 version, but 1.4 is still not launching properly.
I will try to update and let you know if I manage to pull out anything else from this issue.

**Comment by POE-Addon-Launcher** [comment]
@GlitchingCloud  can you use this debugger and send me the log you receive from it?
https://github.com/POE-Addon-Launcher/PoE-Addon-Launcher/files/2418268/b11.zip

**Comment by POE-Addon-Launcher** [comment]
@Razunter  JRE 12 fix is now live.

**Comment by Razunter** [comment]
@POE-Addon-Launcher works now. BTW, you can open multiple settings windows.

**Comment by POE-Addon-Launcher** [comment]
Ah yeah that does seem like I don't want people to be able to do that thanks.
